// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"database/sql"
)

type CuisineType struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}

type Rating struct {
	ID        string         `json:"id"`
	UserID    string         `json:"user_id"`
	RecipeID  string         `json:"recipe_id"`
	Score     int32          `json:"score"`
	Notes     sql.NullString `json:"notes"`
	CreatedAt sql.NullTime   `json:"created_at"`
}

type Recipe struct {
	ID          string         `json:"id"`
	UserID      string         `json:"user_id"`
	Title       string         `json:"title"`
	Description sql.NullString `json:"description"`
	Ingredients sql.NullString `json:"ingredients"`
	Steps       sql.NullString `json:"steps"`
	CuisineType sql.NullString `json:"cuisine_type"`
	PrepTime    sql.NullInt32  `json:"prep_time"`
	PhotoUrl    sql.NullString `json:"photo_url"`
	Notes       sql.NullString `json:"notes"`
	CreatedAt   sql.NullTime   `json:"created_at"`
}

type User struct {
	ID           string         `json:"id"`
	Email        string         `json:"email"`
	Name         sql.NullString `json:"name"`
	AvatarUrl    sql.NullString `json:"avatar_url"`
	CreatedAt    sql.NullTime   `json:"created_at"`
	PasswordHash sql.NullString `json:"password_hash"`
	Role         sql.NullString `json:"role"`
}
