// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: ratings.sql

package sqlc

import (
	"context"
	"database/sql"
)

const deleteRating = `-- name: DeleteRating :exec
DELETE FROM ratings
WHERE recipe_id = ? AND user_id = ?
`

type DeleteRatingParams struct {
	RecipeID string `json:"recipe_id"`
	UserID   string `json:"user_id"`
}

func (q *Queries) DeleteRating(ctx context.Context, arg DeleteRatingParams) error {
	_, err := q.db.ExecContext(ctx, deleteRating, arg.RecipeID, arg.UserID)
	return err
}

const getRecipesByUserSortedByRating = `-- name: GetRecipesByUserSortedByRating :many
SELECT r.id, r.user_id, r.title, r.description, r.ingredients, r.steps, r.cuisine_type, r.prep_time, r.photo_url, r.notes, r.created_at, COALESCE(rt.score, 0) AS rating_score
FROM recipes r
LEFT JOIN ratings rt ON r.id = rt.recipe_id AND rt.user_id = r.user_id
WHERE r.user_id = ?
ORDER BY rating_score DESC, r.created_at DESC
`

type GetRecipesByUserSortedByRatingRow struct {
	ID          string         `json:"id"`
	UserID      string         `json:"user_id"`
	Title       string         `json:"title"`
	Description sql.NullString `json:"description"`
	Ingredients sql.NullString `json:"ingredients"`
	Steps       sql.NullString `json:"steps"`
	CuisineType sql.NullString `json:"cuisine_type"`
	PrepTime    sql.NullInt32  `json:"prep_time"`
	PhotoUrl    sql.NullString `json:"photo_url"`
	Notes       sql.NullString `json:"notes"`
	CreatedAt   sql.NullTime   `json:"created_at"`
	RatingScore int32          `json:"rating_score"`
}

func (q *Queries) GetRecipesByUserSortedByRating(ctx context.Context, userID string) ([]GetRecipesByUserSortedByRatingRow, error) {
	rows, err := q.db.QueryContext(ctx, getRecipesByUserSortedByRating, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetRecipesByUserSortedByRatingRow{}
	for rows.Next() {
		var i GetRecipesByUserSortedByRatingRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Title,
			&i.Description,
			&i.Ingredients,
			&i.Steps,
			&i.CuisineType,
			&i.PrepTime,
			&i.PhotoUrl,
			&i.Notes,
			&i.CreatedAt,
			&i.RatingScore,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSuggestions = `-- name: GetSuggestions :many
SELECT DISTINCT r.id, r.user_id, r.title, r.description, r.ingredients, r.steps, r.cuisine_type, r.prep_time, r.photo_url, r.notes, r.created_at
FROM recipes r
WHERE r.user_id = ?
  AND r.cuisine_type IN (
    SELECT rec.cuisine_type
    FROM recipes rec
    JOIN ratings rat ON rec.id = rat.recipe_id
    WHERE rec.user_id = ?
    GROUP BY rec.cuisine_type
    HAVING AVG(rat.score) >= 4
    ORDER BY AVG(rat.score) DESC
    LIMIT 3
  )
ORDER BY r.created_at DESC
LIMIT 10
`

type GetSuggestionsParams struct {
	UserID   string `json:"user_id"`
	UserID_2 string `json:"user_id_2"`
}

func (q *Queries) GetSuggestions(ctx context.Context, arg GetSuggestionsParams) ([]Recipe, error) {
	rows, err := q.db.QueryContext(ctx, getSuggestions, arg.UserID, arg.UserID_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Recipe{}
	for rows.Next() {
		var i Recipe
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Title,
			&i.Description,
			&i.Ingredients,
			&i.Steps,
			&i.CuisineType,
			&i.PrepTime,
			&i.PhotoUrl,
			&i.Notes,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertRating = `-- name: UpsertRating :exec
INSERT INTO ratings (id, user_id, recipe_id, score, notes)
VALUES (UUID(), ?, ?, ?, ?)
ON DUPLICATE KEY UPDATE score = VALUES(score), notes = VALUES(notes)
`

type UpsertRatingParams struct {
	UserID   string         `json:"user_id"`
	RecipeID string         `json:"recipe_id"`
	Score    int32          `json:"score"`
	Notes    sql.NullString `json:"notes"`
}

func (q *Queries) UpsertRating(ctx context.Context, arg UpsertRatingParams) error {
	_, err := q.db.ExecContext(ctx, upsertRating,
		arg.UserID,
		arg.RecipeID,
		arg.Score,
		arg.Notes,
	)
	return err
}
