// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: recipes.sql

package sqlc

import (
	"context"
	"database/sql"
)

const createRecipe = `-- name: CreateRecipe :execresult
INSERT INTO recipes (id, user_id, title, description, ingredients, steps, cuisine_type, prep_time, photo_url, notes)
VALUES (UUID(), ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateRecipeParams struct {
	UserID      string         `json:"user_id"`
	Title       string         `json:"title"`
	Description sql.NullString `json:"description"`
	Ingredients sql.NullString `json:"ingredients"`
	Steps       sql.NullString `json:"steps"`
	CuisineType sql.NullString `json:"cuisine_type"`
	PrepTime    sql.NullInt32  `json:"prep_time"`
	PhotoUrl    sql.NullString `json:"photo_url"`
	Notes       sql.NullString `json:"notes"`
}

func (q *Queries) CreateRecipe(ctx context.Context, arg CreateRecipeParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createRecipe,
		arg.UserID,
		arg.Title,
		arg.Description,
		arg.Ingredients,
		arg.Steps,
		arg.CuisineType,
		arg.PrepTime,
		arg.PhotoUrl,
		arg.Notes,
	)
}

const deleteRecipe = `-- name: DeleteRecipe :exec
DELETE FROM recipes
WHERE id = ? AND user_id = ?
`

type DeleteRecipeParams struct {
	ID     string `json:"id"`
	UserID string `json:"user_id"`
}

func (q *Queries) DeleteRecipe(ctx context.Context, arg DeleteRecipeParams) error {
	_, err := q.db.ExecContext(ctx, deleteRecipe, arg.ID, arg.UserID)
	return err
}

const getRecipeByID = `-- name: GetRecipeByID :one
SELECT id, user_id, title, description, ingredients, steps, cuisine_type, prep_time, photo_url, notes, created_at FROM recipes
WHERE id = ? AND user_id = ?
`

type GetRecipeByIDParams struct {
	ID     string `json:"id"`
	UserID string `json:"user_id"`
}

func (q *Queries) GetRecipeByID(ctx context.Context, arg GetRecipeByIDParams) (Recipe, error) {
	row := q.db.QueryRowContext(ctx, getRecipeByID, arg.ID, arg.UserID)
	var i Recipe
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Description,
		&i.Ingredients,
		&i.Steps,
		&i.CuisineType,
		&i.PrepTime,
		&i.PhotoUrl,
		&i.Notes,
		&i.CreatedAt,
	)
	return i, err
}

const listRecipesByUser = `-- name: ListRecipesByUser :many
SELECT id, user_id, title, description, ingredients, steps, cuisine_type, prep_time, photo_url, notes, created_at FROM recipes
WHERE user_id = ?
ORDER BY created_at DESC
`

func (q *Queries) ListRecipesByUser(ctx context.Context, userID string) ([]Recipe, error) {
	rows, err := q.db.QueryContext(ctx, listRecipesByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Recipe{}
	for rows.Next() {
		var i Recipe
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Title,
			&i.Description,
			&i.Ingredients,
			&i.Steps,
			&i.CuisineType,
			&i.PrepTime,
			&i.PhotoUrl,
			&i.Notes,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateRecipe = `-- name: UpdateRecipe :exec
UPDATE recipes
SET title = COALESCE(?, title),
    description = COALESCE(?, description),
    ingredients = COALESCE(?, ingredients),
    steps = COALESCE(?, steps),
    cuisine_type = COALESCE(?, cuisine_type),
    prep_time = COALESCE(?, prep_time),
    photo_url = COALESCE(?, photo_url),
    notes = COALESCE(?, notes)
WHERE id = ? AND user_id = ?
`

type UpdateRecipeParams struct {
	Title       string         `json:"title"`
	Description sql.NullString `json:"description"`
	Ingredients sql.NullString `json:"ingredients"`
	Steps       sql.NullString `json:"steps"`
	CuisineType sql.NullString `json:"cuisine_type"`
	PrepTime    sql.NullInt32  `json:"prep_time"`
	PhotoUrl    sql.NullString `json:"photo_url"`
	Notes       sql.NullString `json:"notes"`
	ID          string         `json:"id"`
	UserID      string         `json:"user_id"`
}

func (q *Queries) UpdateRecipe(ctx context.Context, arg UpdateRecipeParams) error {
	_, err := q.db.ExecContext(ctx, updateRecipe,
		arg.Title,
		arg.Description,
		arg.Ingredients,
		arg.Steps,
		arg.CuisineType,
		arg.PrepTime,
		arg.PhotoUrl,
		arg.Notes,
		arg.ID,
		arg.UserID,
	)
	return err
}
